name: translatetribune
description: "Translate Tribune project."
publish_to: 'none'
version: 1.0.2+15

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  # Flutter 3.19.5 • channel stable
  flutter:
    sdk: flutter

  # Routing
  auto_route: 8.1.1

  # Notifications
  flutter_local_notifications: 17.1.0

  # Local database
  drift: 2.17.0
  drift_sqflite: 2.0.1
  sqlite3_flutter_libs: 0.5.21

  # Utils
  intl: 0.19.0
  html: 0.15.4
  url_launcher: 6.2.6
  flutter_launcher_icons: 0.13.1
  share_plus: 9.0.0
  permission_handler: 11.3.1
  timezone: 0.9.3
  app_settings: 5.1.1

  # Code Generation
  get_it: 7.7.0
  freezed: 2.5.2
  json_serializable: 6.7.1
  injectable: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  injectable_generator: 2.6.1
  freezed_annotation: 2.4.1
  flutter_lints: 3.0.0
  auto_route_generator: 8.0.0
  drift_dev: 2.17.0
  flutter_svg: 2.0.10+1
  flutter_native_splash: 2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_mono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto_mono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_mono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
